project:
  type: website

website:
  title: "Designing a Reproducible and Collaborative Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coding.qmd
        text: "Coding as a Lab"
      - href: data.qmd
        text: "Managing your data"
      - href: workflow.qmd
        text: "Analytical workflows"
      - href: preserving.qmd
        text: "Documenting and Preserving Things"
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/reproducible-lab

format:
  html:
    theme: 
      - cosmo
      - rdsstyles.scss
    toc: true
    include-after-body: _footer.html


