project:
  type: website
  title: "Designing a Reproducible and Collaborative Lab (RCL)"
  
website:
  page-navigation: true
  search: 
    location: navbar
  navbar:
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/reproducible-lab    
    
  sidebar:
    style: "docked"
    border: true
    contents:
      - href: index.qmd
        text: "About RCL"
      - section: "Coding as a Lab"
        contents:
          - href: coding.qmd
            text: "Code as scientific product"
          - section: "Leveraging GitHub"
            contents:
              - href: github_intro.qmd
                text: "Short intro to GitHub"
              - href: 01-handson_github_website.qmd
                text: "Hands-on: Using Github's website"
              - href: github_org.qmd
                text: "GitHub organizations for your Lab"
              - href: github_teams.qmd
                text: "Setting up teams to better collaborate"
              - href: git_rstudio.qmd
                text: "Using RStudio, git and GitHub to track your work"
          - section: "Collaborative coding"
            contents:
              - href: collab_pairprog.qmd
                text: "Pair Programming"
              - href: collab_exchange.qmd
                text: "Code Exchange"
              - href: github_workflows.qmd
                text: "Collaborating with GitHub"
              - href: 03-handson_github_workflows.qmd
                text: "Hands-on: Collaborative workflows"
              - href: 02-handson_github_rstudio.qmd
                text: "Hands-on: Branches from RStudio"
          # - section: "Documenting things"
          #   contents:
          #     - href: github_template.qmd
          #       text: "Streamlining code documentation"
      # - section: "Managing your Research data"
      #   contents:
      #       - href: data_mgmt.qmd
      #         text: "What is data management?"
format:
  html:
    theme: 
      - cosmo
      - rdsstyles.scss
    toc: true
    include-after-body: _footer.html


