project:
  type: website
  title: "Designing a Reproducible and Collaborative Lab (RCL)"
  
website:
  page-navigation: true
  search: 
    location: navbar
  navbar:
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/reproducible-lab    
    
  sidebar:
    style: "docked"
    border: true
    contents:
      - href: index.qmd
        text: "About RCL"
      - section: "Coding as a Lab"
        contents:
          - href: coding.qmd
            text: "Code as scientific product"
          - section: "Leveraging GitHub"
            contents:
              - href: github_intro.qmd
                text: "Short intro to GitHub"
              - href: 01-handson_github_website.qmd
                text: "Using Github's website to track your work"
              - href: 02-handson_github_rstudio.qmd
                text: "Using Rstudio, git and GitHub to track your work"
              - href: github_org.qmd
                text: "GitHub organizations"
              - href: github_teams.qmd
                text: "Setting up teams"
          - section: "Collaborative coding"
            contents:
              - href: collab_pairprog.qmd
                text: "Pair Programming"
              - href: collab_exchange.qmd
                text: "Code Exchange"
          - section: "Documenting things"
            contents:
              - href: github_template.qmd
                text: "Streamlining code documentation"
      - section: "Managing your Research data"
        contents:
            - href: data_mgmt.qmd
              text: "What is data management?"
format:
  html:
    theme: 
      - cosmo
      - rdsstyles.scss
    toc: true
    include-after-body: _footer.html


