project:
  type: website
  title: "Designing a Reproducible and Collaborative Lab (RCL)"
  
website:
  page-navigation: true
  search: 
    location: navbar
  navbar:
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/reproducible-lab    
    
  sidebar:
    style: "docked"
    border: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "About RCL"
      - section: "Coding as a Lab"
        contents:
          - href: coding.qmd
            text: "Code as scientific product"
          - section: "Coding together"
            contents:
              - href: github_intro.qmd
                text: "Our tools: git & GitHub"
              - href: 01-handson_github_website.qmd
                text: "Hands-on: Using Github's website"
              - href: github_org.qmd
                text: "GitHub Organizations for your Lab"
              - href: github_teams.qmd
                text: "Setting up Teams to better collaborate"
              - href: git_rstudio.qmd
                text: "Using RStudio, git and GitHub to track your work"
              - href: intro_cli.qmd
                text: "Using the command line"
              - href: git_cli.qmd
                text: "Using git at the command line"
              - href: git_conflicts.qmd
                text: "Managing version conflicts"
              - href: git_further_readings.qmd
                text: "Git and GitHub further readings"
          - section: "Collaborative strategies"
            contents:
              - href: collab_exchange.qmd
                text: "Code Exchange"
              - href: collab_pairprog.qmd
                text: "Pair Programming"
              - href: github_workflows.qmd
                text: "Collaborative workflows: forks & branches"
              - href: 03-handson_github_workflows.qmd
                text: "Hands-on: forks & branches with Github website"
              - href: 02-handson_github_rstudio.qmd
                text: "Hands-on: Branches using RStudio"
          - section: "Streamlining documentation"
            contents:
              - href: github_template.qmd
                text: "Repository template"
      - section: "Managing your Lab data"
        contents:
          - href: data_mgmt.qmd
            text: "What is data management?"
          - href: data_mgmt.qmd
            text: "A few questions"
          - href: datamgmt_plan.qmd
            text: "Plan"
          - href: datamgmt_manage.qmd
            text: "Manage"
      - section: "Preserving things"
        contents:
          - href: datamgmt_prompts-preserve.qmd
            text: "Preservation prompts"
          - href: datamgmt_preserve.qmd
            text: "Preserve your data"
            
format:
  html:
    theme: 
      - cosmo
      - rdsstyles.scss
    toc: true
    include-after-body: _footer.html
# check how to add main font here

