project:
  type: website

website:
  title: "Designing a Reproducible and Collaborative Lab"
  page-navigation: true
  search: 
    location: navbar
  navbar:
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/reproducible-lab    
    
  sidebar:
    align: center
    style: "docked"
    search: true
    contents:    
      - section: "Coding as a Lab"
        contents:
          - href: coding.qmd
            text: "Code as scientific product"
      - section: "Leveraging GitHub"
        contents:
          - href: github_intro.qmd
            text: "Short intro to GitHub"
          - href: github_org.qmd
            text: "GitHub organizations"
          - href: github_teams.qmd
            text: "Setting up teams"
      - section: "Collaborative coding"
        contents:
          - href: collab_pairprog.qmd
            text: "Pair Programming"
          - href: collab_exchange.qmd
            text: "Code Exchange"
      - section: "Documenting things"
        contents:
          - href: github_template.qmd
            text: "Streamlining documentation"

format:
  html:
    theme: 
      - cosmoqmdqmdqmd
      - rdsstyles.scss
    toc: true
    include-after-body: _footer.html


