---
title: "Code as a scientific product"
---

Codes are part of the scientific products your Lab is producing. It is thus important to manage, document, and preserve them as you would do for any other of your scientific products. In this session, we will discuss tools and practices that can ease the management of your codes, as well as develop them in a collaborative way.

## Code repository

As data repositories, code repositories are a great way to preserve and share your code (including with your future self!!). One you might have already heard of is GitHub. However, there are other options such as GitLab, Bitbucket Source Forge, and more.

In this session, we will be focusing on using GitHub to collaborate and keep track of the development of our scripts.

- Quick intro to git & GitHub
  - Why those are tools you want to use
  - GitHub Website interface walk-through
  - Using RStudio
  - At the Command Line

- GitHub Organizations
  - Why do you want one for your Lab
  - set it up
  - manage: teams and settings
  
- Collaborative coding workflows & strategies
  - Pair Programming
  - Code Exchange
  - Branch and fork workflows

- Streamlining documentation with templates
  - Repositories



  
  