---
title: "git_cli"
execute: 
  eval: FALSE
---


## Setup your git profile

### your git identity

If you are not sure if you have already set your git identity, you can check this running this command:

```{bash git config list, eval=FALSE}
git config --global --list
```

If you identity is not set yet, you need to provide your name and email (we recommend to use the same email as used when setting your GitHub account): 

```{bash git identity, eval=FALSE}
git config --global user.name "your Full Name"
git config --global user.email "your Email"
```


##### Optional

Check that everything is correct: 

```{bash git config check, eval=FALSE}
git config --global --list
```

Modify everything at the same time:

```{bash git config edit, eval=FALSE}
git config --global --edit
```

Set your text editor: 

```{bash git config editor, eval=FALSE}
git config --system core.editor nano
```

Here [`nano`](https://www.nano-editor.org) is used as example; you can choose most of the text editor you might have installed on your computer (atom, sublime, notepad++ ...).

Problem with any of those steps? Check out Jenny Brian [Happy git trouble shooting section](http://happygitwithr.com/troubleshooting.html){target="_blank"}


### your GitHub credentials


## Clone a repository

::: {.callout-tip}
If you not have yet your `favorite-desserts` GitHub repository, please follow those [steps](https://ucsb-library-research-data-services.github.io/reproducible-lab/01-handson_github_website.html)
:::


Navigate to a folder where you want to save your repository and run the following command: 

```{bash}
git clone https://github.com/brunj7/favorite-desserts.git
```

you should have a new folder on your local machine:


```{bash}
ls
```

Go inside the repository:

```{bash}
cd favorite-desserts
```

