---
title: "Designing a Reproducible and Collaborative Lab"
---

Workshop Series and Coaching Sessions for Faculty and their Teams


### Topics

- Coding as a lab
- Managing your lab data Automating your analytical workflows
- Documenting & preserving things to make them reusable

### Format

- Scheduled at your convenience
- 4 workshops (2-3h) as a primer on a specific topic
- Personalized coaching sessions focused on lab-specific needs

### Outcomes

- More reproducible management of your lab's scientific products (data, code etc.) 
- Streamlined on- and off -boarding
- Better analytical strategies for collaboration Safety nets for your research lab content 
- More efficient reuse of your work

### Learning Opportunities

- Leverage GitHub organizations to manage your Lab code 
- Develop strategies to centralize and manage your Lab data 
- Protect your Lab scientific products against loss through backup and computing resources strategies
- Set up templates and guidelines on how to document your Lab research and improve its reusability
- Establish Lab standard operating procedures and documentation standards
- Create "good enough" research computing strategies for robust and more reusable code development