---
title: "Choosing a License"
---

It is a good practice to add a license to a repository/project. It will help to clarify what are the expectations regarding using and potentially contributing to this work.

## Code

Here is a good website to choose a license for your code: <https://choosealicense.com/>{target="_blank"}

[Here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository){target="_blank"} is also a good set of instructions on how to make this happen on a GitHub repository: 

Note those type of licensing is more meant for software (such as R packages) rather than analytical scripts. For those scripts, keeping the license minimal such as [MIT](https://choosealicense.com/licenses/mit/){target="_blank"} of [3-Clause BSD](https://choosealicense.com/licenses/bsd-3-clause/){target="_blank"} is our recommendation.


## Data

Technically, facts are not copyrightable. Only interpretations of facts. However, data licensing falls under the content licensing framework that is more related to copyright. Here is the type of licensing that can be used: <https://creativecommons.org/licenses/>{target="_blank"}

**CC0 is recommended for data**

Note that the license type might be dictated by the data repository you choose as most of the data repositories will have one or two licenses to choose from.